define([], function() {
  return {
    "Title": "CopyJet Install – install a template",
    "StepLoad": "Load",
    "StepPreview": "Preview",
    "StepInstall": "Install",
    "StepResult": "Result",
    "Next": "Next",
    "Back": "Back",

    "DropHint": "Drop a CopyJet template (.json) here, or choose one:",
    "ChooseFile": "Choose file",
    "Reading": "Reading the template…",
    "ZipLater": ".zip templates (with content) can be installed from phase 2.",
    "InvalidTemplate": "The file is not a valid CopyJet template",
    "ParseError": "The file is not readable JSON",
    "VersionError": "The template version is not supported",
    "TemplateLabel": "Template",
    "SourceLabel": "Source",
    "CreatedLabel": "Created",
    "ContentsLabel": "Contents",
    "PermissionsChecking": "Checking permissions…",
    "PermissionsMissing": "Installing needs owner permissions on this site. Missing: {0}",
    "PermissionsOk": "Permissions are fine.",

    "PreviewLoading": "Comparing the target site with the template…",
    "PreviewFailed": "The preview could not be created",
    "ColumnInclude": "Install",
    "ColumnKind": "Type",
    "ColumnName": "Name",
    "ColumnStatus": "Status",
    "StatusNew": "new",
    "StatusSame": "already there",
    "StatusDifferent": "differs: {0}",
    "StatusUnsupported": "cannot install: {0}",
    "StatusError": "error: {0}",
    "ExcludedDisabled": "switched off",
    "ExcludedDependency": "skipped because it depends on {0}",
    "ExcludedCycle": "skipped: circular dependency",
    "ConflictModeLabel": "When an item already exists and differs",
    "ModeSkip": "Skip (keep the existing one)",
    "ModeUpdate": "Update (adds and changes, never deletes)",
    "ModeRename": "Create a copy (named \"(copy)\" where possible)",
    "PreviewCounts": "{0} new, {1} already there, {2} different, {3} cannot install",
    "StartInstall": "Start installation",

    "Installing": "Installing: {0} / {1}",
    "Stop": "Stop",
    "LeaveWarning": "The installation is still running. Leaving the page interrupts it.",
    "InstallFailed": "The installation stopped with an unexpected error",

    "ResultTitle": "The installation has finished.",
    "ResultStopped": "You stopped the installation.",
    "CountCreated": "created",
    "CountUpdated": "updated",
    "CountSkipped": "skipped",
    "CountFailed": "failed",
    "CountBlocked": "not installed (dependency)",
    "CountCancelled": "cancelled",
    "CreatedLists": "Lists and libraries on the target site:",
    "NewInstall": "New installation",

    "KindGroup": "Group",
    "KindSiteField": "Site column",
    "KindContentType": "Content type",
    "KindList": "List / library",
    "KindListField": "List column",
    "KindView": "View",

    "LogTitle": "Log",
    "LogAll": "All levels",
    "LogInfo": "info",
    "LogWarn": "warning",
    "LogError": "error",
    "LogEmpty": "No entries yet.",
    "LogExportCsv": "Log CSV",
    "LogExportJson": "Log JSON"
  }
});
