define([], function() {
  return {
    "Title": "CopyJet Install",
    "StepLoad": "Load",
    "StepMapping": "Mapping",
    "StepPreview": "Preview",
    "StepInstall": "Install",
    "StepResult": "Result",
    "SubtitleLoad": "Load a template",
    "SubtitleMapping": "Mapping",
    "SubtitlePreview": "Preview",
    "SubtitleInstall": "Installing",
    "SubtitleResult": "Result",
    "Next": "Next",
    "Back": "Back",
    "DropHint": "Drop the template here (.json or .zip)",
    "Browse": "Browse…",
    "OrFromLibrary": "Or pick from a library / URL",
    "TemplateUrl": "Template URL",
    "TemplateUrlPlaceholder": "https://…/CopyJetTemplates/template.json",
    "LoadFromUrl": "Load from URL",
    "PickFromLibrary": "Pick a file from a library…",
    "Reading": "Reading the template…",
    "InvalidTemplate": "The file is not a valid CopyJet template",
    "ParseError": "The file is not readable JSON",
    "VersionError": "The template version is not supported",
    "UrlError": "The file cannot be downloaded from this URL",
    "Valid": "Valid",
    "FactSource": "Source",
    "FactSchema": "Schema",
    "FactContent": "Contents",
    "FactChecksum": "Checksum",
    "NoChecksum": "—",
    "ChecksumChecking": "checking…",
    "ChecksumOk": "matches",
    "ChecksumMismatch": "differs",
    "ChecksumMismatchNote": "The template content does not match the checksum recorded when it was made: the file was changed or damaged afterwards. You can continue, but only if you know who changed it and why.",
    "ContentSummary": "{0} lists · {1} columns · {2} views",
    "Warning": "Warning",
    "TenantDiffers": "The source tenant differs from the target – match users and terms in the Mapping step; files copied by reference are skipped here.",
    "PermissionsChecking": "Checking permissions…",
    "PermissionsMissing": "Installing needs owner permissions on this site",
    "PermissionsMissingDetail": "Missing: {0}",
    "Phase2": "(phase 2)",
    "Users": "Users",
    "ManagedMetadata": "Managed Metadata",
    "NothingToMap": "The template does not reference users or Managed Metadata terms – nothing to map.",
    "ColName": "Name",
    "ColSourceUser": "Source",
    "ColTargetUser": "Target",
    "ColMethod": "Method",
    "ColStatus": "Status",
    "ColTermPath": "Term path",
    "NotMapped": "Not mapped",
    "PreviewLoading": "Comparing the target site with the template…",
    "PreviewFailed": "The preview could not be created",
    "CountNew": "{0} new",
    "CountSame": "{0} same",
    "CountDifferent": "{0} different",
    "CountProblem": "{0} problems",
    "GlobalMode": "Conflict handling (all)",
    "ModeSkip": "Skip",
    "ModeUpdate": "Update",
    "ModeRename": "Rename",
    "ColSelect": "Select",
    "ColKind": "Type",
    "ColConflict": "Conflict handling",
    "StatusNew": "New",
    "StatusSame": "Same",
    "StatusDifferent": "Different",
    "StatusUnsupported": "Cannot install",
    "StatusError": "Error",
    "Excluded": "Skipped",
    "ExcludedDisabled": "switched off",
    "ExcludedDependency": "depends on: {0}",
    "ExcludedCycle": "circular dependency",
    "ProblemText": "{0}: {1}",
    "ReasonlistMissing": "the list is missing on the target",
    "ReasontitleConflict": "another list already has this title",
    "ReasonidConflict": "another column uses this ID",
    "Reasontaxonomy": "Managed Metadata column – phase 2",
    "ReasontermSetMissing": "the term set (group/set) is not on the target – the Managed Metadata column is not created",
    "ReasonnameConflict": "another content type has this name",
    "Reasontemplate": "different list type on the target",
    "Reasonurl": "the list cannot be created at this URL",
    "ReasonviewType": "only standard (HTML) views can be installed",
    "StartInstall": "Start installation",
    "Installing": "{0}",
    "InstallSteps": "{0} / {1} steps",
    "Preparing": "Preparing…",
    "PhaseGroups": "SharePoint groups ({0})",
    "PhaseSiteFields": "Site columns ({0})",
    "PhaseContentTypes": "Content types ({0})",
    "PhaseLists": "Lists and libraries ({0})",
    "PhaseListFields": "List columns, lookups ({0})",
    "PhaseViews": "Views ({0})",
    "Stop": "Stop",
    "LeaveWarning": "The installation is still running. Leaving the page interrupts it.",
    "InstallFailed": "The installation stopped with an unexpected error",
    "ResultTitle": "The installation has finished",
    "ResultWithErrors": "The installation finished with errors",
    "ResultStopped": "You stopped the installation",
    "Duration": "{0} min {1} s",
    "StatCreated": "Created",
    "StatUpdated": "Updated",
    "StatSkipped": "Skipped",
    "StatWarnError": "Warnings / errors",
    "CreatedItems": "Created items",
    "Warnings": "Warnings",
    "NoWarnings": "No warnings.",
    "AndMore": "… and {0} more",
    "NothingCreated": "Nothing new was created.",
    "DownloadCsv": "Download log (CSV)",
    "DownloadJson": "Log (JSON)",
    "NewInstall": "New installation",
    "KindGroup": "Group",
    "KindSiteField": "Site column",
    "KindContentType": "Content type",
    "KindList": "List",
    "KindLibrary": "Library",
    "KindListField": "List column",
    "KindView": "View",
    "KindPage": "Modern page",
    "PhasePages": "Modern pages ({0})",
    "ContentPages": " · {0} pages",
    "ContentNavigation": " · navigation ({0} links)",
    "ReasonpageExists": "a page with this name exists on the target – replaced only in update mode",
    "KindNavigation": "Navigation",
    "PhaseNavigation": "Navigation, home page ({0})",
    "NavQuickLaunch": "Left menu",
    "NavTopNavigation": "Top menu",
    "NavHomePage": "Home page: {0}",
    "ReasonnewLinks": "{0} new links, appended to the existing ones",
    "ReasonhomePageDiffers": "the target's home page switches to this page",
    "ReasonhomePageMissing": "the page is neither on the target nor in the template",
    "KindFiles": "Files",
    "PhaseFiles": "Files ({0})",
    "ContentFiles": " · {0} files (about {1} MB)",
    "ReasontargetHasFiles": "the target library already has files – only missing ones are added, nothing is overwritten",
    "ReasonotherTenant": "the files are copied by reference from a site of another tenant – they install only within the source tenant and are skipped here",
    "KindItems": "List items",
    "KindItemLookups": "Lookup values",
    "PhaseItems": "List items ({0})",
    "PhaseItemLookups": "Lookup values, second round ({0})",
    "ContentMissing": "The template refers to content that is not in the file. For a template with content, load the whole .zip file.",
    "ContentItems": " · {0} items",
    "MappingAuto": "Lookup order: manual choice, CSV table, same account, same e-mail, domain replacement, then the fallback user. Where none finds anyone, person values stay empty and Created by/Modified by becomes the installing user (noted in the log).",
    "MappingChecking": "Looking people up on the target site…",
    "MappingNotFoundNote": "{0} people were not found on the target site; their values stay empty.",
    "MapSameLogin": "Same account",
    "MapSameEmail": "Same e-mail",
    "MapNotFound": "Not found",
    "TermsMapped": "{0} / {1} terms mapped (by label path)",
    "TermsChecking": "Looking terms up in the target term store…",
    "TermsMissingNote": "Values of terms not found on the target stay empty; the install log lists them.",
    "TermSame": "Same",
    "TermByPath": "By path",
    "TermMissing": "Missing on the target",
    "UsersMapped": "{0} / {1} mapped",
    "DomainReplace": "Domain replacement",
    "CsvImport": "CSV import",
    "DomainFrom": "Source domain",
    "DomainTo": "target domain",
    "Apply": "Apply",
    "Clear": "Clear",
    "CsvLoaded": "CSV: {0} mappings loaded",
    "CsvInvalid": "; invalid lines: {0} (expected source;target)",
    "MethodManual": "Manual",
    "MethodCsv": "CSV",
    "MethodDomain": "Domain replacement",
    "MethodFallback": "Fallback",
    "StatusFound": "Found",
    "ManualPlaceholder": "e-mail or account, Enter",
    "ManualTargetFor": "Target user for {0}",
    "FallbackLabel": "Instead of unmapped people:",
    "FallbackEmpty": "Leave empty + log",
    "FallbackUser": "Fallback user",
    "ReasontargetHasItems": "the target list already has items – nothing is added to avoid duplicates",
    "LogTitle": "Log",
    "LogAll": "All levels",
    "LogInfo": "info",
    "LogWarn": "warning",
    "LogError": "error",
    "LogEmpty": "No entries yet.",
    "ResumeTitle": "An unfinished installation of this template",
    "ResumeText": "Started {0}, last saved {1}. Finished steps: {2}, failed or interrupted: {3}. A resume does not run the finished steps again.",
    "ResumeContinue": "Resume",
    "ResumeNew": "New installation",
    "ResumeChosen": "The installation resumes the earlier run.",
    "ResumeCheckFailed": "Earlier runs could not be read: {0}",
    "StatPrevious": "Done in the earlier run",
    "KindListSecurity": "List permissions",
    "PhaseListSecurity": "List permissions ({0})",
    "ReasoninheritsPermissions": "the target list inherits its permissions – the inheritance is broken and the template's assignments are added",
    "Reasonassignments": "{0} role assignments missing – added, existing ones are kept"
  }
});
