define([], function() {
  return {
    "Title": "CopyJet Install",
    "StepLoad": "Load",
    "StepMapping": "Mapping",
    "StepPreview": "Preview",
    "StepInstall": "Install",
    "StepResult": "Result",
    "SubtitleLoad": "Load a template",
    "SubtitleMapping": "Mapping",
    "SubtitlePreview": "Preview",
    "SubtitleInstall": "Installing",
    "SubtitleResult": "Result",
    "Next": "Next",
    "Back": "Back",
    "DropHint": "Drop the template here (.json or .zip)",
    "Browse": "Browse…",
    "OrFromLibrary": "Or pick from a library / URL",
    "TemplateUrl": "Template URL",
    "TemplateUrlPlaceholder": "https://…/CopyJetTemplates/template.json",
    "LoadFromUrl": "Load from URL",
    "PickFromLibrary": "Pick a file from a library…",
    "Reading": "Reading the template…",
    "ZipLater": ".zip templates (with content) can be installed from phase 2.",
    "InvalidTemplate": "The file is not a valid CopyJet template",
    "ParseError": "The file is not readable JSON",
    "VersionError": "The template version is not supported",
    "UrlError": "The file cannot be downloaded from this URL",
    "Valid": "Valid",
    "FactSource": "Source",
    "FactSchema": "Schema",
    "FactContent": "Contents",
    "FactChecksum": "Checksum",
    "NoChecksum": "— (.zip only)",
    "ContentSummary": "{0} lists · {1} columns · {2} views",
    "Warning": "Warning",
    "TenantDiffers": "The source tenant differs from the target – mapping users and terms arrives in phase 2.",
    "PermissionsChecking": "Checking permissions…",
    "PermissionsMissing": "Installing needs owner permissions on this site",
    "PermissionsMissingDetail": "Missing: {0}",
    "Phase2": "(phase 2)",
    "Users": "Users",
    "ManagedMetadata": "Managed Metadata",
    "NothingToMap": "The template does not reference users or Managed Metadata terms – nothing to map.",
    "MappingLater": "Mapping users and terms arrives in phase 2. Until then these references are skipped (reported in the log).",
    "ColName": "Name",
    "ColSourceUser": "Source",
    "ColTargetUser": "Target",
    "ColMethod": "Method",
    "ColStatus": "Status",
    "ColTermPath": "Term path",
    "NotMapped": "Not mapped",
    "PreviewLoading": "Comparing the target site with the template…",
    "PreviewFailed": "The preview could not be created",
    "CountNew": "{0} new",
    "CountSame": "{0} same",
    "CountDifferent": "{0} different",
    "CountProblem": "{0} problems",
    "GlobalMode": "Conflict handling (all)",
    "ModeSkip": "Skip",
    "ModeUpdate": "Update",
    "ModeRename": "Rename",
    "ColSelect": "Select",
    "ColKind": "Type",
    "ColConflict": "Conflict handling",
    "StatusNew": "New",
    "StatusSame": "Same",
    "StatusDifferent": "Different",
    "StatusUnsupported": "Cannot install",
    "StatusError": "Error",
    "Excluded": "Skipped",
    "ExcludedDisabled": "switched off",
    "ExcludedDependency": "depends on: {0}",
    "ExcludedCycle": "circular dependency",
    "ProblemText": "{0}: {1}",
    "ReasonlistMissing": "the list is missing on the target",
    "ReasontitleConflict": "another list already has this title",
    "ReasonidConflict": "another column uses this ID",
    "Reasontaxonomy": "Managed Metadata column – phase 2",
    "ReasonnameConflict": "another content type has this name",
    "Reasontemplate": "different list type on the target",
    "Reasonurl": "the list cannot be created at this URL",
    "ReasonviewType": "only standard (HTML) views can be installed",
    "StartInstall": "Start installation",
    "Installing": "{0}",
    "InstallSteps": "{0} / {1} steps",
    "Preparing": "Preparing…",
    "PhaseGroups": "SharePoint groups ({0})",
    "PhaseSiteFields": "Site columns ({0})",
    "PhaseContentTypes": "Content types ({0})",
    "PhaseLists": "Lists and libraries ({0})",
    "PhaseListFields": "List columns, lookups ({0})",
    "PhaseViews": "Views ({0})",
    "Stop": "Stop",
    "LeaveWarning": "The installation is still running. Leaving the page interrupts it.",
    "InstallFailed": "The installation stopped with an unexpected error",
    "ResultTitle": "The installation has finished",
    "ResultWithErrors": "The installation finished with errors",
    "ResultStopped": "You stopped the installation",
    "Duration": "{0} min {1} s",
    "StatCreated": "Created",
    "StatUpdated": "Updated",
    "StatSkipped": "Skipped",
    "StatWarnError": "Warnings / errors",
    "CreatedItems": "Created items",
    "Warnings": "Warnings",
    "NoWarnings": "No warnings.",
    "AndMore": "… and {0} more",
    "NothingCreated": "Nothing new was created.",
    "DownloadCsv": "Download log (CSV)",
    "DownloadJson": "Log (JSON)",
    "NewInstall": "New installation",
    "KindGroup": "Group",
    "KindSiteField": "Site column",
    "KindContentType": "Content type",
    "KindList": "List",
    "KindLibrary": "Library",
    "KindListField": "List column",
    "KindView": "View",
    "LogTitle": "Log",
    "LogAll": "All levels",
    "LogInfo": "info",
    "LogWarn": "warning",
    "LogError": "error",
    "LogEmpty": "No entries yet."
  }
});
