define([], function() {
  return {
    "Title": "CopyJet Install – sablon telepítése",
    "StepLoad": "Betöltés",
    "StepPreview": "Előnézet",
    "StepInstall": "Telepítés",
    "StepResult": "Eredmény",
    "Next": "Tovább",
    "Back": "Vissza",

    "DropHint": "Húzd ide a CopyJet-sablont (.json), vagy válaszd ki:",
    "ChooseFile": "Fájl kiválasztása",
    "Reading": "Sablon beolvasása…",
    "ZipLater": "A .zip sablonok (tartalommal) a 2. fázisban lesznek telepíthetők.",
    "InvalidTemplate": "A fájl nem érvényes CopyJet-sablon",
    "ParseError": "A fájl nem olvasható JSON",
    "VersionError": "A sablon verziója nem támogatott",
    "TemplateLabel": "Sablon",
    "SourceLabel": "Forrás",
    "CreatedLabel": "Készült",
    "ContentsLabel": "Tartalom",
    "PermissionsChecking": "Jogosultságok ellenőrzése…",
    "PermissionsMissing": "A telepítéshez tulajdonosi jog kell ezen a site-on. Hiányzik: {0}",
    "PermissionsOk": "Jogosultságok rendben.",

    "PreviewLoading": "A cél site összevetése a sablonnal…",
    "PreviewFailed": "Az előnézet nem készült el",
    "ColumnInclude": "Telepítés",
    "ColumnKind": "Típus",
    "ColumnName": "Név",
    "ColumnStatus": "Állapot",
    "StatusNew": "új",
    "StatusSame": "már megvan",
    "StatusDifferent": "eltér: {0}",
    "StatusUnsupported": "nem telepíthető: {0}",
    "StatusError": "hiba: {0}",
    "ExcludedDisabled": "kikapcsolva",
    "ExcludedDependency": "kimarad, mert ettől függ: {0}",
    "ExcludedCycle": "körkörös függőség miatt kimarad",
    "ConflictModeLabel": "Ha egy elem már létezik és eltér",
    "ModeSkip": "Kihagyás (a meglévő marad)",
    "ModeUpdate": "Frissítés (csak hozzáad és módosít, nem töröl)",
    "ModeRename": "Másolat létrehozása („(copy)” névvel, ahol lehet)",
    "PreviewCounts": "{0} új, {1} már megvan, {2} eltér, {3} nem telepíthető",
    "StartInstall": "Telepítés indítása",

    "Installing": "Telepítés: {0} / {1}",
    "Stop": "Leállítás",
    "LeaveWarning": "A telepítés még fut. Ha elhagyod az oldalt, félbeszakad.",
    "InstallFailed": "A telepítés váratlan hibával leállt",

    "ResultTitle": "A telepítés befejeződött.",
    "ResultStopped": "A telepítést leállítottad.",
    "CountCreated": "létrejött",
    "CountUpdated": "frissült",
    "CountSkipped": "kihagyva",
    "CountFailed": "hiba",
    "CountBlocked": "kimaradt (függőség miatt)",
    "CountCancelled": "megszakítva",
    "CreatedLists": "Listák és tárak a cél site-on:",
    "NewInstall": "Új telepítés",

    "KindGroup": "Csoport",
    "KindSiteField": "Site column",
    "KindContentType": "Tartalomtípus",
    "KindList": "Lista / tár",
    "KindListField": "Lista oszlop",
    "KindView": "Nézet",

    "LogTitle": "Napló",
    "LogAll": "Minden szint",
    "LogInfo": "info",
    "LogWarn": "figyelm.",
    "LogError": "hiba",
    "LogEmpty": "Még nincs bejegyzés.",
    "LogExportCsv": "Napló CSV",
    "LogExportJson": "Napló JSON"
  }
});
