define([], function() {
  return {
    "Title": "CopyJet Install",
    "StepLoad": "Betöltés",
    "StepMapping": "Leképezés",
    "StepPreview": "Előnézet",
    "StepInstall": "Telepítés",
    "StepResult": "Eredmény",
    "SubtitleLoad": "Sablon betöltése",
    "SubtitleMapping": "Leképezés",
    "SubtitlePreview": "Előnézet",
    "SubtitleInstall": "Telepítés",
    "SubtitleResult": "Eredmény",
    "Next": "Tovább",
    "Back": "Vissza",
    "DropHint": "Húzd ide a sablont (.json vagy .zip)",
    "Browse": "Tallózás…",
    "OrFromLibrary": "Vagy válassz tárból / URL-ről",
    "TemplateUrl": "Sablon URL",
    "TemplateUrlPlaceholder": "https://…/CopyJetTemplates/sablon.json",
    "LoadFromUrl": "Betöltés URL-ről",
    "PickFromLibrary": "Fájl kiválasztása tárból…",
    "Reading": "Sablon beolvasása…",
    "InvalidTemplate": "A fájl nem érvényes CopyJet-sablon",
    "ParseError": "A fájl nem olvasható JSON",
    "VersionError": "A sablon verziója nem támogatott",
    "UrlError": "A fájl nem tölthető le erről az URL-ről",
    "Valid": "Érvényes",
    "FactSource": "Forrás",
    "FactSchema": "Séma",
    "FactContent": "Tartalom",
    "FactChecksum": "Ellenőrzőösszeg",
    "NoChecksum": "—",
    "ChecksumChecking": "ellenőrzés…",
    "ChecksumOk": "egyezik",
    "ChecksumMismatch": "eltér",
    "ChecksumMismatchNote": "A sablon tartalma nem egyezik az elkészítéskor rögzített ellenőrzőösszeggel: a fájl utólag módosult vagy sérült. A telepítés folytatható, de csak akkor, ha tudod, ki és miért módosította.",
    "ContentSummary": "{0} lista/tár · {1} oszlop · {2} nézet",
    "Warning": "Figyelmeztetés",
    "TenantDiffers": "A forrás tenant eltér a céltól – a felhasználókat és a termeket a Leképezés lépésben párosítod; a hivatkozással másolt fájlok itt kimaradnak.",
    "PermissionsChecking": "Jogosultságok ellenőrzése…",
    "PermissionsMissing": "A telepítéshez tulajdonosi jog kell ezen a site-on",
    "PermissionsMissingDetail": "Hiányzik: {0}",
    "Phase2": "(2. fázis)",
    "Users": "Felhasználók",
    "ManagedMetadata": "Managed Metadata",
    "NothingToMap": "A sablon nem hivatkozik felhasználókra vagy Managed Metadata termekre – nincs leképezési teendő.",
    "ColName": "Név",
    "ColSourceUser": "Forrás",
    "ColTargetUser": "Cél",
    "ColMethod": "Módszer",
    "ColStatus": "Állapot",
    "ColTermPath": "Term útvonal",
    "NotMapped": "Nincs leképezve",
    "PreviewLoading": "A cél site összevetése a sablonnal…",
    "PreviewFailed": "Az előnézet nem készült el",
    "CountNew": "{0} új",
    "CountSame": "{0} azonos",
    "CountDifferent": "{0} eltérő",
    "CountProblem": "{0} probléma",
    "GlobalMode": "Ütközéskezelés (mindenre)",
    "ModeSkip": "Kihagy",
    "ModeUpdate": "Frissít",
    "ModeRename": "Átnevez",
    "ColSelect": "Kijelölés",
    "ColKind": "Típus",
    "ColConflict": "Ütközéskezelés",
    "StatusNew": "Új",
    "StatusSame": "Azonos",
    "StatusDifferent": "Eltérő",
    "StatusUnsupported": "Nem telepíthető",
    "StatusError": "Hiba",
    "Excluded": "Kimarad",
    "ExcludedDisabled": "kikapcsolva",
    "ExcludedDependency": "ettől függ: {0}",
    "ExcludedCycle": "körkörös függőség",
    "ProblemText": "{0}: {1}",
    "ReasonlistMissing": "a lista nincs meg a célon",
    "ReasontitleConflict": "ezzel a címmel már van egy másik lista",
    "ReasonidConflict": "az azonosítót egy másik oszlop használja",
    "Reasontaxonomy": "Managed Metadata oszlop – a 2. fázisban",
    "ReasontermSetMissing": "a termkészlet (csoport/termkészlet) nincs meg a célon – a Managed Metadata oszlop nem jön létre",
    "ReasonnameConflict": "ezzel a névvel már van egy másik tartalomtípus",
    "Reasontemplate": "eltérő listatípus a célon",
    "Reasonurl": "ezen az URL-en a lista nem hozható létre",
    "ReasonviewType": "csak normál (HTML) nézet telepíthető",
    "StartInstall": "Telepítés indítása",
    "Installing": "{0}",
    "InstallSteps": "{0} / {1} lépés",
    "Preparing": "Előkészítés…",
    "PhaseGroups": "SharePoint-csoportok ({0})",
    "PhaseSiteFields": "Site columnok ({0})",
    "PhaseContentTypes": "Tartalomtípusok ({0})",
    "PhaseLists": "Listák és tárak ({0})",
    "PhaseListFields": "Lista mezők, lookupok ({0})",
    "PhaseViews": "Nézetek ({0})",
    "Stop": "Leállítás",
    "LeaveWarning": "A telepítés még fut. Ha elhagyod az oldalt, félbeszakad.",
    "InstallFailed": "A telepítés váratlan hibával leállt",
    "ResultTitle": "A telepítés befejeződött",
    "ResultWithErrors": "A telepítés hibákkal fejeződött be",
    "ResultStopped": "A telepítést leállítottad",
    "Duration": "{0} perc {1} mp",
    "StatCreated": "Létrejött",
    "StatUpdated": "Frissítve",
    "StatSkipped": "Kihagyva",
    "StatWarnError": "Figyelmeztetés / hiba",
    "CreatedItems": "Létrehozott elemek",
    "Warnings": "Figyelmeztetések",
    "NoWarnings": "Nincs figyelmeztetés.",
    "AndMore": "… és még {0}",
    "NothingCreated": "Nem jött létre új elem.",
    "DownloadCsv": "Napló letöltése (CSV)",
    "DownloadJson": "Napló (JSON)",
    "NewInstall": "Új telepítés",
    "KindGroup": "Csoport",
    "KindSiteField": "Site column",
    "KindContentType": "Tartalomtípus",
    "KindList": "Lista",
    "KindLibrary": "Tár",
    "KindListField": "Lista oszlop",
    "KindView": "Nézet",
    "KindPage": "Modern lap",
    "PhasePages": "Modern lapok ({0})",
    "ContentPages": " · {0} lap",
    "ContentNavigation": " · navigáció ({0} link)",
    "ReasonpageExists": "már van ilyen nevű lap a célon – csak frissítés módban íródik felül",
    "KindNavigation": "Navigáció",
    "PhaseNavigation": "Navigáció, kezdőlap ({0})",
    "NavQuickLaunch": "Bal oldali menü",
    "NavTopNavigation": "Felső menü",
    "NavHomePage": "Kezdőlap: {0}",
    "ReasonnewLinks": "{0} új link, hozzáfűzve a meglévőkhöz",
    "ReasonhomePageDiffers": "a cél kezdőlapja erre a lapra vált",
    "ReasonhomePageMissing": "a lap nincs a célon és a sablonban sem",
    "KindFiles": "Fájlok",
    "PhaseFiles": "Fájlok ({0})",
    "ContentFiles": " · {0} fájl (kb. {1} MB)",
    "ReasontargetHasFiles": "a céltárban már vannak fájlok – csak a hiányzók kerülnek fel, felülírás nélkül",
    "ReasonotherTenant": "a fájlok hivatkozással jönnek egy másik tenant site-járól – csak a forrás tenantjában telepíthetők, itt kimaradnak",
    "KindItems": "Listaelemek",
    "KindItemLookups": "Lookup-értékek",
    "PhaseItems": "Listaelemek ({0})",
    "PhaseItemLookups": "Lookup-értékek, 2. kör ({0})",
    "ContentMissing": "A sablon olyan tartalomra hivatkozik, amely nincs a fájlban. Tartalommal készült sablonnál a teljes .zip fájlt töltsd be.",
    "ContentItems": " · {0} elem",
    "MappingAuto": "Keresési sorrend: kézi választás, CSV-tábla, azonos fiók, azonos e-mail, domaincsere, végül a helyettesítő felhasználó. Akit egyik sem talál, annál a személymező üresen marad, a Létrehozta/Módosította pedig a telepítő lesz (a naplóban jelezve).",
    "MappingChecking": "Felhasználók keresése a cél site-on…",
    "MappingNotFoundNote": "{0} felhasználó nem található a cél site-on; az ő értékeik üresen maradnak.",
    "MapSameLogin": "Azonos fiók",
    "MapSameEmail": "Azonos e-mail",
    "MapNotFound": "Nem található",
    "TermsMapped": "{0} / {1} term leképezve (címke-útvonal alapján)",
    "TermsChecking": "Termek keresése a cél termtárban…",
    "TermsMissingNote": "A célon nem talált termek értékei üresen maradnak; a telepítés naplója felsorolja őket.",
    "TermSame": "Egyezik",
    "TermByPath": "Útvonal szerint",
    "TermMissing": "Hiányzik a célon",
    "UsersMapped": "{0} / {1} leképezve",
    "DomainReplace": "Domaincsere",
    "CsvImport": "CSV import",
    "DomainFrom": "Forrás tartomány",
    "DomainTo": "cél tartomány",
    "Apply": "Alkalmaz",
    "Clear": "Törlés",
    "CsvLoaded": "CSV: {0} leképezés betöltve",
    "CsvInvalid": "; hibás sorok: {0} (forrás;cél alak kell)",
    "MethodManual": "Kézi",
    "MethodCsv": "CSV",
    "MethodDomain": "Domaincsere",
    "MethodFallback": "Helyettesítő",
    "StatusFound": "Talált",
    "ManualPlaceholder": "e-mail vagy fiók, Enter",
    "ManualTargetFor": "Cél felhasználó: {0}",
    "FallbackLabel": "Nem leképezett felhasználók helyett:",
    "FallbackEmpty": "Üresen hagyás + napló",
    "FallbackUser": "Helyettesítő felhasználó",
    "ReasontargetHasItems": "a céllistában már vannak elemek – nem ír bele, hogy ne duplikáljon",
    "LogTitle": "Napló",
    "LogAll": "Minden szint",
    "LogInfo": "info",
    "LogWarn": "figyelm.",
    "LogError": "hiba",
    "LogEmpty": "Még nincs bejegyzés.",
    "ResumeTitle": "Félbemaradt telepítés ennél a sablonnál",
    "ResumeText": "Indítva: {0}, utoljára mentve: {1}. Kész lépések: {2}, hibás vagy félbemaradt: {3}. Folytatáskor a kész lépések nem futnak újra.",
    "ResumeContinue": "Folytatás",
    "ResumeNew": "Új telepítés",
    "ResumeChosen": "A telepítés az előző futás folytatása lesz.",
    "ResumeCheckFailed": "Az előző futások nem olvashatók: {0}",
    "StatPrevious": "Előző futásban kész",
    "KindListSecurity": "Listajogosultság",
    "PhaseListSecurity": "Listajogosultságok ({0})",
    "ReasoninheritsPermissions": "a céllista örökli a jogosultságokat – az öröklés megszűnik, és a sablon hozzárendelései kerülnek rá",
    "Reasonassignments": "{0} szerepkör-hozzárendelés hiányzik – hozzáadja, a meglévőket nem veszi el"
  }
});
