// Generates TypeScript artifacts from schema/copyjet.v1.schema.json (the single source of truth):
//   src/core/model/generated/copyjet.v1.ts   - TypeScript types (json-schema-to-typescript)
//   src/core/schema/generated/schemaV1.ts    - the schema itself as a TS module (bundled for AJV)
// Usage: npm run gen:types            (write files)
//        npm run gen:types -- --check (fail if generated files are out of date)
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const schemaPath = resolve(root, 'schema/copyjet.v1.schema.json');
const typesOut = resolve(root, 'src/core/model/generated/copyjet.v1.ts');
const schemaOut = resolve(root, 'src/core/schema/generated/schemaV1.ts');
const check = process.argv.includes('--check');

const header =
  '/* eslint-disable */\n' +
  '// AUTO-GENERATED by scripts/gen-types.mjs from schema/copyjet.v1.schema.json – do not edit by hand.\n' +
  '// Run `npm run gen:types` after changing the schema.\n';

const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));

const pascal = (s) => s.replace(/(^|[^A-Za-z0-9])([A-Za-z0-9])/g, (_m, _p, c) => c.toUpperCase());

// Name types after their $defs key via "title": objects get the "I" prefix (repo convention), others stay plain.
const forTypes = structuredClone(schema);
// Drop validation-only constructs that do not change the shape but make the generator emit duplicate aliases
// (if/then/allOf conditionals, descriptions next to $ref).
const simplify = (node) => {
  if (Array.isArray(node)) return node.forEach(simplify);
  if (!node || typeof node !== 'object') return;
  delete node.if;
  delete node.then;
  delete node.else;
  if (Array.isArray(node.allOf) && node.allOf.every((s) => s.if)) delete node.allOf;
  if (node.$ref) delete node.description;
  Object.values(node).forEach(simplify);
};
simplify(forTypes);
for (const [key, def] of Object.entries(forTypes.$defs)) {
  def.title = def.type === 'object' ? `I${pascal(key)}` : pascal(key);
}
forTypes.title = 'ICopyJetTemplate';

const types = await compile(forTypes, 'ICopyJetTemplate', {
  bannerComment: header,
  unreachableDefinitions: true,
  additionalProperties: false,
  strictIndexSignatures: false,
  format: true,
  style: { singleQuote: true, printWidth: 120 },
  cwd: dirname(schemaPath)
});

const schemaModule =
  header.replace('/* eslint-disable */\n', '') +
  '// The v1 JSON Schema bundled as a module so AJV can use it in the browser and in Jest.\n' +
  `export const copyJetSchemaV1: Record<string, unknown> = ${JSON.stringify(schema, null, 2)};\n`;

let stale = false;
for (const [path, content] of [[typesOut, types], [schemaOut, schemaModule]]) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : '';
  if (current === content) continue;
  if (check) {
    console.error(`Out of date: ${path}`);
    stale = true;
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`Wrote ${path}`);
  }
}
if (stale) {
  console.error('Run `npm run gen:types`.');
  process.exit(1);
}
