define([], function() {
  return {
    "Title": "CopyJet Setup – create a template",
    "StepSelect": "Select",
    "StepOptions": "Options",
    "StepSummary": "Summary",
    "StepExport": "Export",
    "Next": "Next",
    "Back": "Back",

    "Loading": "Discovering the site…",
    "LoadError": "The site could not be discovered",
    "DiscoverPartialError": "Some artifact types could not be read: {0}",
    "WholeSite": "Whole site",
    "CategoryList": "Lists and libraries",
    "CategoryGroup": "SharePoint groups",
    "CategorySiteField": "Site columns",
    "CategoryContentType": "Content types",
    "SelectedOf": "{0} / {1} selected",
    "Columns": "Columns",
    "Views": "Views",
    "ItemCount": "{0} items",
    "UnsupportedLIST_TEMPLATE_UNSUPPORTED": "CopyJet does not copy this list type yet",
    "UnsupportedVIEW_TYPE_UNSUPPORTED": "Only standard (HTML) views can be copied",
    "UnsupportedOther": "Cannot be copied",
    "SelectionSummary": "Selected",
    "NothingSelected": "Select at least one item.",

    "NameLabel": "Template name",
    "NameRequired": "Give the template a name.",
    "DefaultTemplateName": "{0} template",
    "DescriptionLabel": "Description (optional)",
    "ContentLaterInfo": "In this version the template contains the structure (lists, columns, views, content types, groups). Copying items, files, pages and navigation comes in the next phases.",

    "SummaryIntro": "The template will contain:",
    "KindGroup": "SharePoint group",
    "KindSiteField": "Site column",
    "KindContentType": "Content type",
    "KindList": "List or library",
    "KindListField": "List column",
    "KindView": "View",
    "CreateTemplate": "Create template",

    "ExportRunning": "Reading: {0}",
    "ExportDone": "The template is ready.",
    "ExportFailed": "The template could not be created",
    "ExportStopped": "Stopped.",
    "Stop": "Stop",
    "Download": "Download",
    "TemplateInvalid": "The template does not match the schema",
    "MissingTitle": "{0} dependencies are not selected: the template installs without them, but items pointing to them will be incomplete.",
    "AddMissingAndRebuild": "Add all and rebuild",
    "NewTemplate": "New template",

    "LogTitle": "Log",
    "LogAll": "All levels",
    "LogInfo": "info",
    "LogWarn": "warning",
    "LogError": "error",
    "LogEmpty": "No entries yet.",
    "LogExportCsv": "Log CSV",
    "LogExportJson": "Log JSON"
  }
});
