define([], function() {
  return {
    "Title": "CopyJet Setup",
    "StepSelect": "Select",
    "StepOptions": "Options",
    "StepSummary": "Summary",
    "StepExport": "Export",
    "SubtitleSelect": "Choose what to copy",
    "SubtitleOptions": "Options",
    "SubtitleSummary": "Summary",
    "SubtitleExport": "Export",
    "Next": "Next",
    "Back": "Back",
    "Loading": "Discovering the site…",
    "LoadError": "The site could not be discovered",
    "DiscoverPartialError": "Some artifact types could not be read: {0}",
    "SearchPlaceholder": "Search lists, libraries, columns",
    "WholeSite": "Whole site",
    "CategoryLists": "Lists",
    "CategoryLibraries": "Document libraries",
    "CategoryGroups": "SharePoint groups",
    "CategoryColumnsAndTypes": "Site columns and content types",
    "SelectedOf": "{0} / {1} selected",
    "Columns": "Columns",
    "Views": "Views",
    "ItemCount": "{0} items",
    "UnsupportedLIST_TEMPLATE_UNSUPPORTED": "CopyJet does not copy this list type yet",
    "UnsupportedVIEW_TYPE_UNSUPPORTED": "only standard (HTML) views can be copied",
    "UnsupportedOther": "cannot be copied",
    "SelectionSummary": "Selected",
    "SideLists": "Lists",
    "SideLibraries": "Libraries",
    "SideGroups": "Groups",
    "SideSiteColumns": "Site columns",
    "SideContentTypes": "Content types",
    "SideColumns": "List columns",
    "SideViews": "Views",
    "SideNote": "Copying content (items, files), pages and navigation can be switched on in later phases.",
    "NothingSelected": "Select at least one item.",
    "ColName": "Name",
    "ColType": "Type",
    "ColCopy": "Copy",
    "ColVersionsMembers": "Versions / members",
    "TypeList": "List",
    "TypeLibrary": "Library",
    "TypeGroup": "Group",
    "TypeSiteColumn": "Site column",
    "TypeContentType": "Content type",
    "CopyStructure": "Structure only",
    "CopyStructureContent": "Structure + content",
    "CopyGroup": "Group + permissions",
    "MembersOff": "Members: off",
    "Off": "Off",
    "Dash": "—",
    "Phase2": "(phase 2)",
    "GlobalSettings": "Global settings",
    "NameLabel": "Template name",
    "NameRequired": "Give the template a name.",
    "DefaultTemplateName": "{0} template",
    "DescriptionLabel": "Description (optional)",
    "PreserveAuthors": "Keep author, editor and dates",
    "MaxFileSize": "Max. file size",
    "FormatLabel": "Format",
    "FormatJson": ".json (structure)",
    "FormatZip": ".zip (with content)",
    "CopyMode": "Copy mode",
    "FolderFilter": "Folder filter (optional)",
    "FolderFilterPlaceholder": "e.g. /2026",
    "CopyVersions": "Copy version history",
    "VersionsNote": "By default only the current version goes into the template. Switched on, the package grows with the number of versions.",
    "IncludeMembers": "Copy members",
    "MembersNote": "Members need user mapping between tenants.",
    "ClosePanel": "Close panel",
    "SelectRowHint": "Select a row to see its options.",
    "Checking": "Checking dependencies…",
    "CheckFailed": "The dependency check failed",
    "MissingTitle": "{0} dependencies are not selected",
    "MissingNote": "The template installs without them, but items pointing to them will be incomplete:",
    "AddAll": "Add all",
    "StatLists": "Lists and libraries",
    "StatColumns": "Columns",
    "StatViews": "Views",
    "StatGroups": "Groups",
    "ColArea": "Area",
    "ColContent": "Contents",
    "ColNote": "Note",
    "AreaStructure": "Structure",
    "AreaGroups": "Groups",
    "StructureText": "{0} site columns, {1} content types, {2} lists/libraries, {3} list columns, {4} views",
    "StructureNote": "Lookups in dependency order",
    "GroupsNote": "Without members",
    "PersonalNote": "The template contains the author's e-mail address. Store it only where it is allowed.",
    "CreateTemplate": "Create template",
    "ExportRunning": "Reading: {0}",
    "ExportSteps": "{0} / {1} steps",
    "ExportDoneLabel": "Reading finished",
    "ExportDone": "The template is ready.",
    "ExportFailed": "The template could not be created",
    "ExportStopped": "Stopped.",
    "TemplateInvalid": "The template does not match the schema",
    "Output": "Output",
    "OutputPending": "{0} — once ready",
    "SaveToLibrary": "Save to the CopyJetTemplates library",
    "Stop": "Stop",
    "Download": "Download",
    "NewTemplate": "New template",
    "KindGroup": "SharePoint group",
    "KindSiteField": "Site column",
    "KindContentType": "Content type",
    "KindList": "List or library",
    "KindListField": "List column",
    "KindView": "View",
    "FormatAuto": "set by the content choice",
    "StatItems": "Items",
    "AreaContent": "Content",
    "ContentText": "{0} lists, about {1} items",
    "ContentNote": "Lookups in a second round, people by e-mail",
    "PersonalNoteContent": "The template contains personal data (authors, editors). Store it only where it is allowed.",
    "KindItems": "List items",
    "KindItemLookups": "Lookup values",
    "LogTitle": "Log",
    "LogAll": "All levels",
    "LogInfo": "info",
    "LogWarn": "warning",
    "LogError": "error",
    "LogEmpty": "No entries yet.",
    "LogExportCsv": "Download log (CSV)",
    "LogExportJson": "Log (JSON)"
  }
});
