define([], function() {
  return {
    "Title": "CopyJet Setup",
    "StepSelect": "Kiválasztás",
    "StepOptions": "Opciók",
    "StepSummary": "Összesítő",
    "StepExport": "Export",
    "SubtitleSelect": "Forrás kiválasztása",
    "SubtitleOptions": "Opciók",
    "SubtitleSummary": "Összesítő",
    "SubtitleExport": "Export",
    "Next": "Tovább",
    "Back": "Vissza",
    "Loading": "A site feltérképezése…",
    "LoadError": "A site feltérképezése nem sikerült",
    "DiscoverPartialError": "Néhány elemtípust nem sikerült beolvasni: {0}",
    "SearchPlaceholder": "Keresés listák, tárak, oszlopok között",
    "WholeSite": "Teljes site",
    "CategoryLists": "Listák",
    "CategoryLibraries": "Dokumentumtárak",
    "CategoryGroups": "SharePoint-csoportok",
    "CategoryColumnsAndTypes": "Site columnok és tartalomtípusok",
    "SelectedOf": "{0} / {1} kiválasztva",
    "Columns": "Oszlopok",
    "Views": "Nézetek",
    "ItemCount": "{0} elem",
    "UnsupportedLIST_TEMPLATE_UNSUPPORTED": "ezt a listatípust a CopyJet még nem másolja",
    "UnsupportedVIEW_TYPE_UNSUPPORTED": "csak a normál (HTML) nézetek másolhatók",
    "UnsupportedOther": "nem másolható",
    "SelectionSummary": "Kiválasztva",
    "SideLists": "Listák",
    "SideLibraries": "Tárak",
    "SideGroups": "Csoportok",
    "SideSiteColumns": "Site columnok",
    "SideContentTypes": "Tartalomtípusok",
    "SideColumns": "Lista oszlopok",
    "SideViews": "Nézetek",
    "SideNote": "A tartalom (elemek, fájlok), a lapok és a navigáció másolása a következő fázisokban kapcsolható be.",
    "NothingSelected": "Válassz ki legalább egy elemet.",
    "ColName": "Név",
    "ColType": "Típus",
    "ColCopy": "Másolás",
    "ColVersionsMembers": "Verziók / tagok",
    "TypeList": "Lista",
    "TypeLibrary": "Tár",
    "TypeGroup": "Csoport",
    "TypeSiteColumn": "Site column",
    "TypeContentType": "Tartalomtípus",
    "CopyStructure": "Csak szerkezet",
    "CopyStructureContent": "Szerkezet + tartalom",
    "CopyGroup": "Csoport + jogosultság",
    "MembersOff": "Tagok: ki",
    "Off": "Ki",
    "Dash": "—",
    "Phase2": "(2. fázis)",
    "GlobalSettings": "Globális beállítások",
    "NameLabel": "A sablon neve",
    "NameRequired": "Adj nevet a sablonnak.",
    "DefaultTemplateName": "{0} sablon",
    "DescriptionLabel": "Leírás (nem kötelező)",
    "PreserveAuthors": "Szerző, módosító és dátumok megőrzése",
    "MaxFileSize": "Max. fájlméret",
    "FormatLabel": "Formátum",
    "FormatJson": ".json (szerkezet)",
    "FormatZip": ".zip (tartalommal)",
    "CopyMode": "Másolás módja",
    "FolderFilter": "Mappa szűrő (nem kötelező)",
    "FolderFilterPlaceholder": "pl. /2026",
    "CopyVersions": "Verzióelőzmények másolása",
    "VersionsNote": "Alapértelmezetten csak az aktuális verzió kerül a sablonba. Bekapcsolva a csomag mérete a verziók számával nő.",
    "IncludeMembers": "Tagok másolása",
    "MembersNote": "A tagok tenantok között felhasználó-leképezést igényelnek.",
    "ClosePanel": "Panel bezárása",
    "SelectRowHint": "Válassz egy sort a beállításaihoz.",
    "Checking": "Függőségek ellenőrzése…",
    "CheckFailed": "A függőségek ellenőrzése nem sikerült",
    "MissingTitle": "{0} függőség nincs kiválasztva",
    "MissingNote": "A sablon nélkülük is telepíthető, de a rájuk mutató elemek hiányosak lesznek:",
    "AddAll": "Mind hozzáadása",
    "ContentMissingTitle": "{0} lookup-céllista tartalom nélkül kerül a sablonba",
    "ContentMissingNote": "A tartalommal másolt listák lookupjai ezekre a listákra mutatnak; az elemeik nélkül a lookup-értékek üresen maradnak:",
    "AddContent": "Tartalom bekapcsolása",
    "StatLists": "Listák és tárak",
    "StatColumns": "Oszlopok",
    "StatViews": "Nézetek",
    "StatGroups": "Csoportok",
    "ColArea": "Terület",
    "ColContent": "Tartalom",
    "ColNote": "Megjegyzés",
    "AreaStructure": "Szerkezet",
    "AreaGroups": "Csoportok",
    "StructureText": "{0} site column, {1} tartalomtípus, {2} lista/tár, {3} lista oszlop, {4} nézet",
    "StructureNote": "Lookupok függőségi sorrendben",
    "GroupsNote": "Tagok nélkül",
    "PersonalNote": "A sablon a készítő e-mail-címét tartalmazza. Csak jogosult helyre mentsd.",
    "CreateTemplate": "Sablon készítése",
    "ExportRunning": "Kiolvasás: {0}",
    "ExportSteps": "{0} / {1} lépés",
    "ExportDoneLabel": "Kiolvasás kész",
    "ExportDone": "A sablon elkészült.",
    "ExportFailed": "A sablon készítése nem sikerült",
    "ExportStopped": "Leállítva.",
    "TemplateInvalid": "A sablon nem felel meg a sémának",
    "Output": "Kimenet",
    "OutputPending": "{0} — elkészülte után",
    "SaveToLibrary": "Mentés a CopyJetTemplates tárba",
    "Stop": "Leállítás",
    "Download": "Letöltés",
    "NewTemplate": "Új sablon",
    "KindGroup": "SharePoint-csoport",
    "KindSiteField": "Site column",
    "KindContentType": "Tartalomtípus",
    "KindList": "Lista vagy tár",
    "KindListField": "Lista oszlop",
    "KindView": "Nézet",
    "FormatAuto": "a tartalom szerint automatikus",
    "StatItems": "Elemek",
    "AreaContent": "Tartalom",
    "ContentText": "{0} lista, kb. {1} elem",
    "ContentNote": "Lookupok második körben, felhasználók e-mail szerint",
    "PersonalNoteContent": "A sablon személyes adatokat tartalmaz (szerzők, módosítók). Csak jogosult helyre mentsd.",
    "KindItems": "Listaelemek",
    "KindItemLookups": "Lookup-értékek",
    "LogTitle": "Napló",
    "LogAll": "Minden szint",
    "LogInfo": "info",
    "LogWarn": "figyelm.",
    "LogError": "hiba",
    "LogEmpty": "Még nincs bejegyzés.",
    "LogExportCsv": "Napló letöltése (CSV)",
    "LogExportJson": "Napló (JSON)"
  }
});
