define([], function() {
  return {
    "Title": "CopyJet Setup – sablon készítése",
    "StepSelect": "Kiválasztás",
    "StepOptions": "Opciók",
    "StepSummary": "Összesítő",
    "StepExport": "Export",
    "Next": "Tovább",
    "Back": "Vissza",

    "Loading": "A site feltérképezése…",
    "LoadError": "A site feltérképezése nem sikerült",
    "DiscoverPartialError": "Néhány elemtípust nem sikerült beolvasni: {0}",
    "WholeSite": "Teljes site",
    "CategoryList": "Listák és tárak",
    "CategoryGroup": "SharePoint-csoportok",
    "CategorySiteField": "Site columnok",
    "CategoryContentType": "Tartalomtípusok",
    "SelectedOf": "{0} / {1} kiválasztva",
    "Columns": "Oszlopok",
    "Views": "Nézetek",
    "ItemCount": "{0} elem",
    "UnsupportedLIST_TEMPLATE_UNSUPPORTED": "Ezt a listatípust a CopyJet még nem másolja",
    "UnsupportedVIEW_TYPE_UNSUPPORTED": "Csak a normál (HTML) nézetek másolhatók",
    "UnsupportedOther": "Nem másolható",
    "SelectionSummary": "Kiválasztva",
    "NothingSelected": "Válassz ki legalább egy elemet.",

    "NameLabel": "A sablon neve",
    "NameRequired": "Adj nevet a sablonnak.",
    "DefaultTemplateName": "{0} sablon",
    "DescriptionLabel": "Leírás (nem kötelező)",
    "ContentLaterInfo": "Ebben a verzióban a sablon a szerkezetet tartalmazza (listák, oszlopok, nézetek, tartalomtípusok, csoportok). Az elemek, fájlok, lapok és a navigáció másolása a következő fázisokban érkezik.",

    "SummaryIntro": "A sablonba kerül:",
    "KindGroup": "SharePoint-csoport",
    "KindSiteField": "Site column",
    "KindContentType": "Tartalomtípus",
    "KindList": "Lista vagy tár",
    "KindListField": "Lista oszlop",
    "KindView": "Nézet",
    "CreateTemplate": "Sablon készítése",

    "ExportRunning": "Kiolvasás: {0}",
    "ExportDone": "A sablon elkészült.",
    "ExportFailed": "A sablon készítése nem sikerült",
    "ExportStopped": "Leállítva.",
    "Stop": "Leállítás",
    "Download": "Letöltés",
    "TemplateInvalid": "A sablon nem felel meg a sémának",
    "MissingTitle": "{0} függőség nincs kiválasztva: a sablon ezek nélkül is telepíthető, de a rájuk mutató elemek hiányosak lesznek.",
    "AddMissingAndRebuild": "Mind hozzáadása és újrakészítés",
    "NewTemplate": "Új sablon",

    "LogTitle": "Napló",
    "LogAll": "Minden szint",
    "LogInfo": "info",
    "LogWarn": "figyelm.",
    "LogError": "hiba",
    "LogEmpty": "Még nincs bejegyzés.",
    "LogExportCsv": "Napló CSV",
    "LogExportJson": "Napló JSON"
  }
});
